import "@/public/styles/globals.scss";
import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import { Suspense } from "react";
import Script from "next/script";

import NavBar from "./components/NavBar/NavBar";
import Footer from "./components/Footer/Footer";
const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <Script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
          integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
          crossOrigin="anonymous"
        ></Script>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
          integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
          crossOrigin="anonymous"
        ></Script>
      </head>
      <body className={inter.className}>
        <div className="container-app">
        <Suspense fallback={<div>Loading...</div>}>
          <NavBar />
          {children}
          <Footer />
        </Suspense>
        </div>
        
      </body>
    </html>
  );
}
